[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "flocs"
version = "6.2.0"
description = ""
requires-python = ">3.9"
dependencies = ["flocs-runners", "numpy","structlog", "typer", "packaging", "python-casacore", "losoto", "spinifex", "toil[cwl]>=9"]

[project.scripts]
flocs-run = "flocs_runners.flocs_run:main"

[tool.setuptools]
packages = ["flocs-runners"]

[tool.uv.sources]
flocs-runners = { path = "flocs-runners", editable = true }
