# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: pipeline parameters

on:
  schedule:
      - cron: "0 0 * * 1"
  push:
    branches: [ fedora-py3 ]
  pull_request:
    branches: [ fedora-py3 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12
    - name: Setup dependencies
      run: |
          sudo apt -y install git jq wget
          wget https://github.com/mikefarah/yq/releases/download/v4.45.4/yq_linux_amd64 -O yq
          chmod u+x yq
          pip install uv
          uv pip install --system numpy losoto python-casacore cwltool
          uv pip install --system git+https://github.com/tikk3r/flocs.git
    - name: Generate templates
      run: |
          git clone https://git.astron.nl/RD/LINC.git
          cwltool --make-template LINC/workflows/HBA_calibrator.cwl > template_linc_calibrator.yml
          cwltool --make-template LINC/workflows/HBA_target.cwl > template_linc_target.yml
          ./yq -o=json template_linc_calibrator.yml > template_linc_calibrator.json
          ./yq -o=json template_linc_target.yml > template_linc_target.json
          export LINC_DATA_ROOT=$PWD/LINC
          export VLBI_DATA_ROOT=$PWD/LINC
          flocs-run linc calibrator --config-only /dev/null
          flocs-run linc target --config-only --cal-solutions /dev/null /dev/null
    - name: Check LINC options
      run: |
          jq -r 'keys[] as $k | "\($k)"' mslist_unknown_LINC_calibrator.json > keys_flocs_calibrator
          jq -r 'keys[] as $k | "\($k)"' mslist_unknown_LINC_target.json > keys_flocs_target
          jq -r 'keys[] as $k | "\($k)"' template_linc_calibrator.json > keys_template_calibrator
          jq -r 'keys[] as $k | "\($k)"' template_linc_target.json > keys_template_target
          sed -i '/solveralgorithm/d' keys_flocs*
          sed -i '/solveralgorithm/d' keys_template*
          if [[ $(diff -q keys_template_calibrator keys_flocs_calibrator) ]]; then echo "Keys do not match LINC calibrator" && diff --side-by-side --suppress-common-lines keys_flocs_calibrator keys_template_calibrator && exit 1; fi
          if [[ $(diff -q keys_template_target keys_flocs_target) ]]; then echo "Keys do not match LINC target" && diff --side-by-side --suppress-common-lines keys_flocs_target keys_template_target && exit 1; fi

